### PR TITLE
Fix @npm directory, Bootstrap4 no support BootstrapThemeAsset.php

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no

### CODE REVIEW

**Comment by hiqsol** [comment]
Thank you!

**Comment by bizley** [comment]
Shouldn't [composer.assets.json](https://github.com/yiisoft/yii-bootstrap4/blob/master/composer.assets.json) be changed as well for non-foxy fallback?

**Comment by terabytesoftw** [comment]
The file [composer.assets.json](https://github.com/yiisoft/yii-bootstrap4/blob/master/composer.assets.json) is generated automatically by [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin), but @hiqsol updated the AssetBundle and will be working with Foxy that works with npm in an excellent way the assets. You have to create a pr to delete the file. the file you can delete does not fulfill any function at the moment.

**Comment by machour** [comment]
@terabytesoftw I think that `composer.assets.json` is still needed for users not using foxy/foxy in their main project.

As I understand it, we are going to support both methods in all packages requiring assets. If the main project requiring those packages use foxy/foxy, the package.json file will be read, if not, composer.assets.json (as long as you configure the merge-plugin to pick those).

**Comment by terabytesoftw** [comment]
@machour It would not work because @hiqsol changed the route of the Assets [BootstrapAsset.php](https://github.com/yiisoft/yii-bootstrap4/blob/master/src/BootstrapAsset.php), It is mandatory to use Foxy.

**Comment by machour** [comment]
You're right. I'll give this a try later, but I think that we could (and should) always support both mechanism in order to avoid forcing the user to use a specific method.

We could have a special alias that resolves the package in `vendor/asset-foo` or `node_modules/foo` accordingly.

**Comment by terabytesoftw** [comment]
Let me try to see if I can add an alias and thus support both methods as you mention it.

**Comment by terabytesoftw** [comment]
@machour reviewing everything I think we should only support `foxy`, so we work only with a plugin, and so we have the assets independently, to make functions both methods you have to configure the `composer-merge-plugin `also in the  `composer.json`, but the same will work both, if you add the asset to the `composer.json` directly we would lose the independence of the assets, in the package.

Conclusion must work with `foxy`, anyway I think that today almost all have **installed nodejs and npm**.

**Comment by machour** [comment]
@terabytesoftw The proposition is to use something like this in the `composer.json` files of yii packages to make it neutral:

```js
{
    "name": "yiisoft/yii-something",
   // ...
    "extra": {
        // if the user is using foxy, this will hint it to load the `package.json` file
        // @see https://github.com/fxpio/foxy/blob/c66b0e60a449074373cd34f4ae93a23049443b6c/Resources/doc/usage.md#with-the-composers-extra-option
        "foxy": true, 
        // if he or she is using merge-plugin instead, this will get loaded by the plugin
        "merge-plugin": { 
            "include": [
                "composer.assets.json",
            ],
        }
    }
}
```

And always provide both `package.json` and `composer.assets.json`. 

This should work just fine.

**Pull request merged**
